### ISSUE TITLE
Deployed testclusters sometimes fail to create working openstack-cloud-controller-manager

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#46]
The openstack-cloud-controller-manager sometimes fails with:
```
I0831 09:08:12.862233       1 serving.go:331] Generated self-signed cert in-memory                                                      
W0831 09:08:13.094402       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This m
ight not work.                                                                                                                          
I0831 09:08:13.098977       1 controllermanager.go:127] Version: v0.0.0-master+$Format:%h$                                  
W0831 09:08:13.204420       1 openstack.go:303] New openstack client created failed with config: Authentication failed                  
F0831 09:08:13.204468       1 controllermanager.go:131] Cloud provider could not be initialized: could not init cloud provider "openstac
k": Authentication failed                                                                                                               
goroutine 1 [running]:                                                                                                                  
```

**Comment by garloff** [comment]
Looks like we need tenant-id in the cloud.conf file.

**Comment by garloff** [comment]
This seems to have fixed the issue.
